/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculateNumbers;

/**
 *
 * @author sophia
 */
public class caculator extends javax.swing.JFrame {
    private double total1 = 0.0; 
    private double total2 = 0.0; //final total
    private char operator;

    
    public void getOperator(String btnText){
        operator = btnText.charAt(0);
        total1 = total1 + Double.parseDouble(displayTextField.getText());
        displayTextField.setText("");
    }
    
    /**
     * Creates new form caculator
     */
    public caculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTextField = new javax.swing.JTextField();
        calculatorPanel = new javax.swing.JPanel();
        nineBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        displayTextField.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        displayTextField.setForeground(new java.awt.Color(51, 51, 51));
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTextFieldActionPerformed(evt);
            }
        });

        nineBtn.setBackground(new java.awt.Color(255, 255, 255));
        nineBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        nineBtn.setForeground(new java.awt.Color(51, 51, 51));
        nineBtn.setText("9");
        nineBtn.setBorder(null);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        eightBtn.setBackground(new java.awt.Color(255, 255, 255));
        eightBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        eightBtn.setForeground(new java.awt.Color(51, 51, 51));
        eightBtn.setText("8");
        eightBtn.setBorder(null);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        sevenBtn.setBackground(new java.awt.Color(255, 255, 255));
        sevenBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        sevenBtn.setForeground(new java.awt.Color(51, 51, 51));
        sevenBtn.setText("7");
        sevenBtn.setBorder(null);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        sixBtn.setBackground(new java.awt.Color(255, 255, 255));
        sixBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        sixBtn.setForeground(new java.awt.Color(51, 51, 51));
        sixBtn.setText("6");
        sixBtn.setBorder(null);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        fiveBtn.setBackground(new java.awt.Color(255, 255, 255));
        fiveBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        fiveBtn.setForeground(new java.awt.Color(51, 51, 51));
        fiveBtn.setText("5");
        fiveBtn.setBorder(null);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        fourBtn.setBackground(new java.awt.Color(255, 255, 255));
        fourBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        fourBtn.setForeground(new java.awt.Color(51, 51, 51));
        fourBtn.setText("4");
        fourBtn.setBorder(null);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        threeBtn.setBackground(new java.awt.Color(255, 255, 255));
        threeBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        threeBtn.setForeground(new java.awt.Color(51, 51, 51));
        threeBtn.setText("3");
        threeBtn.setBorder(null);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        twoBtn.setBackground(new java.awt.Color(255, 255, 255));
        twoBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        twoBtn.setForeground(new java.awt.Color(51, 51, 51));
        twoBtn.setText("2");
        twoBtn.setBorder(null);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        oneBtn.setBackground(new java.awt.Color(255, 255, 255));
        oneBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        oneBtn.setForeground(new java.awt.Color(51, 51, 51));
        oneBtn.setText("1");
        oneBtn.setBorder(null);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        zeroBtn.setBackground(new java.awt.Color(255, 255, 255));
        zeroBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        zeroBtn.setForeground(new java.awt.Color(51, 51, 51));
        zeroBtn.setText("0");
        zeroBtn.setBorder(null);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        dotBtn.setBackground(new java.awt.Color(255, 255, 255));
        dotBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        dotBtn.setForeground(new java.awt.Color(51, 51, 51));
        dotBtn.setText(".");
        dotBtn.setBorder(null);
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });

        divideBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        divideBtn.setForeground(new java.awt.Color(51, 51, 51));
        divideBtn.setText("/");
        divideBtn.setBorder(null);
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        multiplyBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        multiplyBtn.setForeground(new java.awt.Color(51, 51, 51));
        multiplyBtn.setText("*");
        multiplyBtn.setActionCommand("");
        multiplyBtn.setBorder(null);
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });

        minusBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        minusBtn.setForeground(new java.awt.Color(51, 51, 51));
        minusBtn.setText("-");
        minusBtn.setBorder(null);
        minusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtnActionPerformed(evt);
            }
        });

        plusBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        plusBtn.setForeground(new java.awt.Color(51, 51, 51));
        plusBtn.setText("+");
        plusBtn.setBorder(null);
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(204, 204, 255));
        clearBtn.setFont(new java.awt.Font("Rubik", 0, 20)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(51, 51, 51));
        clearBtn.setText("C");
        clearBtn.setBorder(null);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(255, 153, 153));
        equalBtn.setFont(new java.awt.Font("Rubik", 1, 20)); // NOI18N
        equalBtn.setForeground(new java.awt.Color(51, 51, 51));
        equalBtn.setText("=");
        equalBtn.setBorder(null);
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calculatorPanelLayout = new javax.swing.GroupLayout(calculatorPanel);
        calculatorPanel.setLayout(calculatorPanelLayout);
        calculatorPanelLayout.setHorizontalGroup(
            calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, calculatorPanelLayout.createSequentialGroup()
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(calculatorPanelLayout.createSequentialGroup()
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(threeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dotBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(minusBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(divideBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, calculatorPanelLayout.createSequentialGroup()
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calculatorPanelLayout.setVerticalGroup(
            calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatorPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(calculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(calculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayTextField)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(calculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTextFieldActionPerformed
       int liste[] = new int[9]; 
       
    }//GEN-LAST:event_displayTextFieldActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
       switch(operator){
               case '/' : total2 = total1 / Double.parseDouble(displayTextField.getText());
                             break;
               case '*' : total2 = total1 * Double.parseDouble(displayTextField.getText());
                             break;
               case '-' : total2 = total1 - Double.parseDouble(displayTextField.getText());
                             break;
               case '+' : total2 = total1 + Double.parseDouble(displayTextField.getText());
                             break;
        }
        
        displayTextField.setText(Double.toString(total2));
        total1=0.0;
    }//GEN-LAST:event_equalBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        String BtnText = displayTextField.getText() + zeroBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        String BtnText = displayTextField.getText() + fourBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_fourBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        String BtnText = displayTextField.getText() + eightBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        String BtnText = displayTextField.getText() + nineBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
        
    }//GEN-LAST:event_nineBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        total2 = 0.0;
        displayTextField.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        String BtnText = displayTextField.getText() + sevenBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        String BtnText = sixBtn.getText() + displayTextField.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_sixBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        String BtnText = displayTextField.getText() + fiveBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        String BtnText = displayTextField.getText() + threeBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_threeBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        String BtnText = displayTextField.getText() + twoBtn.getText();
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_twoBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        String BtnText = displayTextField.getText() + oneBtn.getText();
        //String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_oneBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        /*total1 = total1 + Double.parseDouble(displayTextField.getText());
        displayTextField.setText("");*/
        String buttonText = plusBtn.getText();
        
        getOperator(buttonText);
        
    }//GEN-LAST:event_plusBtnActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        String BtnText = displayTextField.getText() + dotBtn.getText() ;
        String displayText = displayTextField.getText();
        displayTextField.setText(BtnText);
    }//GEN-LAST:event_dotBtnActionPerformed

    private void minusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBtnActionPerformed
        String buttonText = minusBtn.getText();
        getOperator(buttonText);
    }//GEN-LAST:event_minusBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        String buttonText = multiplyBtn.getText();
        getOperator(buttonText);
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        String buttonText = divideBtn.getText();
        getOperator(buttonText);
    }//GEN-LAST:event_divideBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calculatorPanel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
